yaml   name: Build and Push Docker Image

   on:
     push:
       branches:
         - master

   jobs:
     build:
       runs-on: ubuntu-latest

       steps:
         - name: Checkout repository
           uses: actions/checkout@v2 

         - name: Set up Docker Buildx
           uses: docker/setup-buildx-action@v1

         - name: Log in to Docker Hub
           run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin  # Аутентификация в Docker Hub

         - name: Build and Push Docker Image
           run: |
             docker build -t your-dockerhub-username/flask-app .
             docker push your-dockerhub-username/flask-app:latest 
